#!/bin/bash

# Bitcoin Legacy Wallet Scanner - Installer Script
# Ubuntu/Debian автоматическая установка

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   print_error "Не запускайте этот скрипт от root пользователя!"
   print_warning "Создайте обычного пользователя и запустите от него"
   exit 1
fi

# Check Ubuntu/Debian
if ! command -v apt &> /dev/null; then
    print_error "Этот скрипт предназначен только для Ubuntu/Debian"
    exit 1
fi

print_status "🚀 Установка Bitcoin Legacy Wallet Scanner"
print_status "=========================================="

# Update system
print_status "Обновление системы..."
sudo apt update

# Install system dependencies
print_status "Установка системных зависимостей..."
sudo apt install -y python3 python3-pip python3-venv python3-dev build-essential

# Install Bitcoin Core
print_status "Установка Bitcoin Core..."
if ! command -v bitcoind &> /dev/null; then
    print_status "Добавление PPA Bitcoin Core..."
    sudo add-apt-repository -y ppa:bitcoin/bitcoin
    sudo apt update
    sudo apt install -y bitcoind bitcoin-cli
    print_success "Bitcoin Core установлен"
else
    print_success "Bitcoin Core уже установлен"
fi

# Create virtual environment
print_status "Создание виртуального окружения Python..."
python3 -m venv venv
source venv/bin/activate

# Upgrade pip
print_status "Обновление pip..."
pip install --upgrade pip

# Install Python dependencies
print_status "Установка Python зависимостей..."
pip install -r requirements.txt

# Create output directory
print_status "Создание выходной директории..."
mkdir -p out
chmod 700 out

# Create Bitcoin configuration
print_status "Настройка Bitcoin Core..."
mkdir -p ~/.bitcoin

if [ ! -f ~/.bitcoin/bitcoin.conf ]; then
    cat > ~/.bitcoin/bitcoin.conf << EOF
# Bitcoin Core Configuration
# Generated by installer script

# Basic settings
daemon=1
server=1
rpcuser=bitcoin_user
rpcpassword=$(openssl rand -hex 32)
rpcallowip=127.0.0.1
rpcbind=127.0.0.1

# For scanner functionality
txindex=1
blockfilterindex=1

# Network (uncomment one)
# mainnet (default)
# testnet=1
# regtest=1

# Performance
dbcache=450
maxorphantx=10
maxmempool=50
mempoolexpiry=72

# Logging
debug=rpc
logips=1
EOF
    print_success "Конфигурация Bitcoin Core создана"
else
    print_warning "Конфигурация Bitcoin Core уже существует"
fi

# Create systemd service for Bitcoin Core
print_status "Создание systemd сервиса для Bitcoin Core..."
sudo tee /etc/systemd/system/bitcoind.service > /dev/null << EOF
[Unit]
Description=Bitcoin daemon
After=network.target

[Service]
Type=forking
User=$USER
Group=$USER
ExecStart=/usr/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid
PIDFile=/run/bitcoind/bitcoind.pid
Restart=on-failure
RestartSec=10

# Make /run/bitcoind
RuntimeDirectory=bitcoind

# Hardening measures
PrivateTmp=true
ProtectSystem=strict
NoNewPrivileges=true
PrivateDevices=true

[Install]
WantedBy=multi-user.target
EOF

# Create runtime directory
sudo mkdir -p /run/bitcoind
sudo chown $USER:$USER /run/bitcoind

# Enable and start Bitcoin Core service
print_status "Запуск Bitcoin Core сервиса..."
sudo systemctl daemon-reload
sudo systemctl enable bitcoind
sudo systemctl start bitcoind

# Wait for Bitcoin Core to start
print_status "Ожидание запуска Bitcoin Core..."
sleep 5

# Check Bitcoin Core status
if bitcoin-cli getblockchaininfo > /dev/null 2>&1; then
    print_success "Bitcoin Core запущен и отвечает"
else
    print_warning "Bitcoin Core не отвечает, проверьте логи: journalctl -u bitcoind"
fi

# Create desktop shortcut
print_status "Создание ярлыка на рабочем столе..."
cat > ~/Desktop/bitcoin-scanner.desktop << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Bitcoin Legacy Scanner
Comment=Bitcoin Legacy Wallet Scanner
Exec=$PWD/venv/bin/python3 $PWD/btc_legacy_scanner.py
Icon=terminal
Terminal=true
Categories=Utility;Network;
EOF

chmod +x ~/Desktop/bitcoin-scanner.desktop

# Create launcher script
print_status "Создание скрипта запуска..."
cat > run_scanner.sh << 'EOF'
#!/bin/bash
# Bitcoin Legacy Scanner Launcher

cd "$(dirname "$0")"
source venv/bin/activate

echo "🚀 Запуск Bitcoin Legacy Scanner..."
echo "📁 Директория: $(pwd)"
echo "🐍 Python: $(which python3)"
echo ""

# Check if Bitcoin Core is running
if ! bitcoin-cli getblockchaininfo > /dev/null 2>&1; then
    echo "❌ Bitcoin Core не запущен!"
    echo "Запустите: sudo systemctl start bitcoind"
    exit 1
fi

# Check blockchain sync status
SYNC_STATUS=$(bitcoin-cli getblockchaininfo | grep -o '"blocks":[0-9]*' | cut -d: -f2)
SYNC_HEADERS=$(bitcoin-cli getblockchaininfo | grep -o '"headers":[0-9]*' | cut -d: -f2)

if [ "$SYNC_STATUS" != "$SYNC_HEADERS" ]; then
    echo "⚠️  Внимание: Блокчейн не полностью синхронизирован"
    echo "   Блоки: $SYNC_STATUS / $SYNC_HEADERS"
    echo "   Рекомендуется дождаться полной синхронизации"
    echo ""
fi

echo "✅ Bitcoin Core готов к работе"
echo ""

# Run scanner
python3 btc_legacy_scanner.py "$@"
EOF

chmod +x run_scanner.sh

# Create test script
print_status "Создание тестового скрипта..."
cat > test_scanner.sh << 'EOF'
#!/bin/bash
# Test Bitcoin Legacy Scanner

cd "$(dirname "$0")"
source venv/bin/activate

echo "🧪 Тестирование Bitcoin Legacy Scanner..."
echo "========================================"

# Test 1: Check dependencies
echo "1. Проверка зависимостей..."
python3 -c "import coincurve; print('✅ coincurve доступен')" 2>/dev/null || \
python3 -c "import ecdsa; print('✅ ecdsa доступен')" 2>/dev/null || \
echo "❌ Ни coincurve, ни ecdsa не доступны"

# Test 2: Check Bitcoin Core
echo "2. Проверка Bitcoin Core..."
if bitcoin-cli getblockchaininfo > /dev/null 2>&1; then
    echo "✅ bitcoin-cli доступен"
    BLOCKS=$(bitcoin-cli getblockchaininfo | grep -o '"blocks":[0-9]*' | cut -d: -f2)
    echo "   Блоков: $BLOCKS"
else
    echo "❌ bitcoin-cli недоступен"
fi

# Test 3: Performance test
echo "3. Тест производительности..."
python3 test_performance.py

echo ""
echo "🎉 Тестирование завершено!"
EOF

chmod +x test_scanner.sh

# Final instructions
print_success "🎉 Установка завершена успешно!"
echo ""
echo "📋 Следующие шаги:"
echo "1. Дождитесь полной синхронизации Bitcoin Core:"
echo "   bitcoin-cli getblockchaininfo"
echo ""
echo "2. Запустите сканер:"
echo "   ./run_scanner.sh"
echo ""
echo "3. Или протестируйте производительность:"
echo "   ./test_scanner.sh"
echo ""
echo "4. Для TUI режима:"
echo "   ./run_scanner.sh"
echo ""
echo "5. Для headless режима:"
echo "   ./run_scanner.sh --headless --start"
echo ""
echo "📁 Файлы:"
echo "   - Основной скрипт: btc_legacy_scanner.py"
echo "   - Конфигурация: config.yaml"
echo "   - Запуск: run_scanner.sh"
echo "   - Тест: test_scanner.sh"
echo "   - Результаты: ./out/"
echo ""
echo "⚠️  ВАЖНО: Этот инструмент создает приватные ключи!"
echo "   Используйте ТОЛЬКО для образовательных целей!"
echo ""
echo "🔗 Документация: README.md"
echo "📖 Помощь: ./run_scanner.sh --help"
